import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def generate_and_save_gp_plot(csv_filename, output_image="gp_performance_comparison.png"):
    try:
        # Load the CSV generated by your GProcess::writeToCSV function [cite: 56, 63]
        df = pd.read_csv(csv_filename)
    except FileNotFoundError:
        print(f"Error: {csv_filename} not found. Please run your C++ engine first.")
        return

    # Sort by TrueValue to create a continuous curve for better visualization of the CI [cite: 49]
    df = df.sort_values(by='TrueValue').reset_index(drop=True)
    
    plt.figure(figsize=(12, 8))
    
    # Plotting True Data points [cite: 16]
    plt.scatter(df.index, df['TrueValue'], color='black', s=12, label='True Values', alpha=0.5)

    # Initial Hyperparameters (Blue) [cite: 56]
    # 95% CI is defined as 1.96 * standard deviation [cite: 16]
    init_ci = 1.96 * df['InitStd']
    plt.plot(df.index, df['InitMean'], color='tab:blue', linewidth=2, label='Initial Mean Prediction')
    plt.fill_between(df.index, 
                    df['InitMean'] - init_ci, 
                    df['InitMean'] + init_ci, 
                    color='tab:blue', alpha=0.15, label='Initial 95% Confidence Interval')

    # Optimized/Learned Parameters (Red) [cite: 55, 56]
    opt_ci = 1.96 * df['OptStd']
    plt.plot(df.index, df['OptMean'], color='tab:red', linewidth=2, label='Optimized Mean Prediction')
    plt.fill_between(df.index, 
                    df['OptMean'] - opt_ci, 
                    df['OptMean'] + opt_ci, 
                    color='tab:red', alpha=0.3, label='Optimized 95% Confidence Interval')

    # Formatting according to HW4 requirements [cite: 4, 11]
    plt.title('Gaussian Process Regression: Learning Hyperparameters via Gradient Descent', fontsize=14)
    plt.xlabel('Samples (Sorted by True Value)', fontsize=12)
    plt.ylabel('Target Value', fontsize=12)
    plt.legend(loc='upper left', frameon=True)
    plt.grid(True, linestyle='--', alpha=0.4)
    
    # Save the figure to the local directory [cite: 63, 64]
    plt.tight_layout()
    plt.savefig(output_image, dpi=300)
    print(f"Plot successfully saved as: {output_image}")
    plt.show()

if __name__ == "__main__":
    generate_and_save_gp_plot('results.csv')